#!/bin/bash
#
#   deploy-diablo-worker - deploy diablo on a worker node
#
#   Assume diablo is installed on the current environment under the path
#   "$HOME/install/diablo" and setup anything necessary under the path
#   "$HOME/deploy/diablo" to be ready to run.
#
#   The current environment can be configured to run as a diablo primary node
#   or secondary node.
#

set -e

script_name='deploy-diablo-worker'
install_root="${HOME}/install/diablo"
deploy_root="${HOME}/deploy/diablo"


# Utility functions - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

fatal() {
    local msg="$1" ; shift

    exec >&2

    echo "${script_name}: ${msg}"
    echo
    echo "Usage: $0 primary <port>                           (1)"
    echo "       $0 secondary <addr:port> [<number>]         (2)"
    echo

    exit 1
}


# Prepare deployment  - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

prepare() {
    if [ ! -d "${deploy_root}" ] ; then
	mkdir -p "${deploy_root}"
    fi
}


# Primary deployment  - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

deploy_primary() {
    if [ $# -lt 1 ] ; then
	fatal "missing port operand"
    elif [ $# -lt 2 ] ; then
	fatal "missing nsecondary operand"
    elif [ $# -gt 2 ] ; then
	fatal "unexpected operand '$3'"
    fi

    local port="$1" ; shift
    local nsecondary="$1" ; shift

    prepare

    mkdir "${deploy_root}/primary"
    echo "${port}" > "${deploy_root}/primary/port"
    echo "${nsecondary}" > "${deploy_root}/primary/nsecondary"
}


# Secondary deployment  - - - - - - - - - - - - - - - - - - - - - - - - - - - -

deploy_secondary() {
    if [ $# -lt 1 ] ; then
	fatal "missing addr:port operand"
    elif [ $# -lt 2 ] ; then
	fatal "missing region operand"
    elif [ $# -gt 3 ] ; then
	fatal "unexpected operand '$4'"
    fi

    local primary="$1" ; shift
    local region="$1" ; shift
    local number="$1"
    local i

    if [ "x${number}" = 'x' ] ; then
	number=1
    else
	shift
    fi

    prepare

    for i in $(seq 0 $(( number - 1 ))) ; do
	mkdir "${deploy_root}/secondary${i}"
	echo "${primary}" > "${deploy_root}/secondary${i}/primary"
	echo "${region}" > "${deploy_root}/secondary${i}/region"
    done
}


# Main script - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ $# -lt 1 ] ; then
    fatal "missing node type ('primary' | 'secondary') operand"
fi

node_type="$1" ; shift

case "${node_type}" in
    'primary')
	deploy_primary "$@"
	;;
    'secondary')
	deploy_secondary "$@"
	;;
    *)
	fatal "unknown node type: '${node_type}'"
	;;
esac
