#!/bin/bash

set -e

script_name='quorum-ibft'
install_root="${HOME}/install/quorum"
deploy_root="${HOME}/deploy/quorum-ibft"


# Utility functions - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

fatal() {
    local msg="$1" ; shift

    exec >&2

    echo "${script_name}: ${msg}"
    echo
    echo "Usage: $0 start (1)"
    echo "       $0 stop (2)"
    echo "       $0 kill (3)"
    echo
    echo "Either start (1), gracefully stop (2) or kill (3) the nodes deployed"
    echo "on this worker"

    exit 1
}

setup_environment() {
    if [ ! -e "${install_root}" ] ; then
	fatal "cannot find quorum install at '${install_root}'"
    fi

    export PATH="${install_root}/build/bin:${PATH}"
    export PATH="${install_root}/istanbul-tools/build/bin:${PATH}"

    if ! command -v 'geth' > '/dev/null' 2> '/dev/null' ; then
	fatal "cannot find geth executable in '${install_root}'"
    fi

    if ! command -v 'istanbul' > '/dev/null' 2> '/dev/null' ; then
	fatal "cannot find istanbul executable in '${install_root}'"
    fi
}


# Actions - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

start() {
    local dir pid port rpcport

    if [ $# -gt 0 ] ; then
	fatal "unexpected operand '$1'"
    fi

    export PRIVATE_CONFIG=ignore

    for dir in "${deploy_root}/n"* ; do
	if [ -d "${dir}" ] ; then
	    port="$(cat "${dir}/port")"
	    rpcport="$(cat "${dir}/rpcport")"

	    if ! echo "${port}" | grep -Pq '^\d+$' ; then
		fatal "cannot find port in '${dir}/port'"
	    fi

	    if ! echo "${rpcport}" | grep -Pq '^\d+$' ; then
		fatal "cannot find rpc port in '${dir}/rpcport'"
	    fi

	    geth --datadir "${dir}" \
		 --allow-insecure-unlock \
		 --nodiscover \
		 --istanbul.blockperiod 5 \
		 --syncmode full \
		 --mine \
		 --miner.threads 1 \
		 --verbosity 3 \
		 --networkid 10 \
		 --ws \
		 --ws.addr 0.0.0.0 \
		 --ws.port "${rpcport}" \
		 --ws.api admin,eth,debug,miner,net,txpool,personal,web3,istanbul \
		 --ws.origins "*" \
		 --emitcheckpoints \
		 --port "${port}" \
		 > "${dir}/out" 2> "${dir}/err" &
	    pid=$!

	    echo ${pid} > "${dir}/pid"
	fi
    done

    sleep 10
}

_kill() {
    local sig="$1" ; shift
    local dir pid dead

    for dir in "${deploy_root}/n"* ; do
	if [ ! -d "${dir}" ] ; then
	    continue
	elif [ ! -f "${dir}/pid" ] ; then
	    continue
	fi

	pid="$(cat "${dir}/pid")"

	if echo "${pid}" | grep -Pq '^\d+$' ; then
	    kill "${sig}" ${pid} 2> '/dev/null' || true
	fi

	dead=0
	for i in $(seq 1 5) ; do
	    if ! ps ${pid} > '/dev/null' ; then
		dead=1
		break
	    fi

	    sleep 1
	done

	if [ ${dead} -eq 0 ] ; then
	    kill -KILL ${pid} 2> '/dev/null' || true
	fi

	rm "${dir}/pid"
    done
}

stop() {
    if [ $# -gt 0 ] ; then
	fatal "unexpected operand '$1'"
    fi

    _kill -INT
}

nkill() {
    if [ $# -gt 0 ] ; then
	fatal "unexpected operand '$1'"
    fi

    _kill -KILL
}


# Main script - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

setup_environment

if [ $# -lt 1 ] ; then
    fatal "missing action operand"
fi

action="$1" ; shift

case "${action}" in
    'kill')
	nkill "$@"
	;;
    'start')
	start "$@"
	;;
    'stop')
	stop "$@"
	;;
    *)
	fatal "unknown action: '${action}'"
	;;
esac
