#!/bin/bash
#
#   install-diablo-worker - install diablo on a worker
#

set -e

diablo_path="$1" ; shift

if ! command -v 'sudo' > '/dev/null' ; then
    echo "Cannot find command 'sudo'" >&2
    exit 1
fi

# Install common utilities as well as golang if not yet installed.
#
if ! command -v 'go' > '/dev/null' ; then
    sudo -n apt-get install -yy 'make' 'golang' 'rsync'
fi

# Create an install dir if not already there.
#
if [ ! -e 'install' ] ; then
    mkdir 'install'
fi

rsync -aAHX "${diablo_path}/" 'install/diablo/' > '/dev/null' 2> '/dev/null'
(
    cd 'install/diablo'

    # Avoid modification outside of this repository.
    # This is important because some other installed software could use
    # different versions of Go.
    #
    export GOPATH="${PWD}/go"

    make diablo
)
