#!/bin/bash
#
#   install-diablo-worker - install diablo on a worker
#

set -e

diablo_path="$1"

if ! command -v 'sudo' > '/dev/null' ; then
    echo "Cannot find command 'sudo'" >&2
    exit 1
fi

# Install common utilities as well as golang if not yet installed.
#
if ! command -v 'make' > '/dev/null' \
	|| ! command -v 'go' > '/dev/null' \
	|| ! test -d '/usr/lib/go-1.16/bin' \
	|| ! command -v 'rsync' > '/dev/null'
then
    sudo -n apt-get install -yy 'make' 'golang-1.16' 'rsync'
fi

# Create an install dir if not already there.
#
if [ ! -e 'install' ] ; then
    mkdir 'install'
fi

# If no source path is specified, install dependencies only.
#
if [ "x${diablo_path}" = 'x' ] ; then
    exit 0
fi

# Synch from sources (brought here by install-diablo-dev.pm).
#
if ! rsync -aAHX --delete --exclude='/go/pkg' "${diablo_path}/" \
     'install/diablo/' > '/dev/null' 2> '/dev/null'
then
    echo "Cannot rsync from sources '${diablo_path}'"
    exit 1
fi

(
    cd 'install/diablo'

    export PATH="/usr/lib/go-1.16/bin:${PATH}"

    # Avoid modification outside of this repository.
    # This is important because some other installed software could use
    # different versions of Go.
    #
    export GOPATH="${PWD}/go"

    make diablo
)
