#!/bin/bash
#
#   install-diablo - install diablo
#

set -e

diablo_url='https://github.com/NatoliChris/diablo-benchmark.git'
diablo_checkout='v2'

if ! command -v 'sudo' > '/dev/null' ; then
    echo "Cannot find command 'sudo'" >&2
    exit 1
fi

while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ; do
    echo 'Waiting for release of dpkg/apt locks'
    sleep 5
done

# Install common utilities as well as golang.
#
sudo -n apt-get -o DPkg::Lock::Timeout=1200 install -yy 'git' 'make' \
     'golang-1.16'

# Create an install dir if not already there.
#
if [ ! -e 'install' ] ; then
    mkdir 'install'
fi

if [ -e 'install/diablo' ] ; then
    sudo rm -rf 'install/diablo'
fi

# Clone Diablo from the official repository and build it.
#
git clone "${diablo_url}" 'install/diablo'
(
    cd 'install/diablo'

    export PATH="/usr/lib/go-1.16/bin:${PATH}"

    git checkout "${diablo_checkout}"

    # Avoid modification outside of this repository.
    # This is important because some other installed software could use
    # different versions of Go.
    #
    export GOPATH="${PWD}/go"

    make reqs
    make diablo
)
