#!/bin/bash
#
#   prepare-install - prepare an apt based system to install packages
#

set -e


if ! command -v 'sudo' > '/dev/null' ; then
    echo "Cannot find command 'sudo'" >&2
    exit 1
fi


mp="${PWD}"
while ! mountpoint --quiet "${mp}" ; do
    mp="${mp%/*}"
    if [ "x${mp}" = 'x' ] ; then
	mp='/'
    fi
done
part="$(mount | grep ' on '"${mp}"' ' | cut -d' ' -f1)"
dev="$(basename "$(readlink -f "/sys/class/block/${part##*/}/..")")"
sudo growpart "/dev/${dev}" 1 || true
sudo resize2fs "${part}" || true


while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ; do
    echo 'Waiting for release of dpkg/apt locks'
    sleep 5
done

sudo -n apt-get -o DPkg::Lock::Timeout=1200 update -yy

while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ; do
    echo 'Waiting for release of dpkg/apt locks'
    sleep 5
done

sudo -n apt-get -o DPkg::Lock::Timeout=1200 install 'psmisc'
